### ISSUE TITLE
Unexpected duplicate "text-decoration" 

### ISSUE THREAD

**Issue by margittennosaar** [Krazza/recipeapp#4]
https://github.com/Krazza/recipeapp/blob/ac8ff7a0ae9079bbb96b646862124704e3c9eab7/src/components/NewRecipe.css#L76

**Comment by Krazza** [comment]
Header.css, HomeCard.css, NewRecipe.css, RecipeEntry.css, VideoBanner.css to a shortened version of property "text-decoration".
